# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '123.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 571)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(24, 24, 24, 0)
        self.verticalLayout_2.setSpacing(18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout_2.addWidget(self.TitleLabel)
        self.SmoothScrollArea = SmoothScrollArea(Form)
        self.SmoothScrollArea.setStyleSheet("background: transparent; border: none")
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 640, 514))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SubtitleLabel_2 = SubtitleLabel(self.scrollAreaWidgetContents)
        self.SubtitleLabel_2.setText("")
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.verticalLayout_7.addWidget(self.SubtitleLabel_2)
        self.CaptionLabel_10 = CaptionLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CaptionLabel_10.sizePolicy().hasHeightForWidth())
        self.CaptionLabel_10.setSizePolicy(sizePolicy)
        self.CaptionLabel_10.setText("")
        self.CaptionLabel_10.setWordWrap(True)
        self.CaptionLabel_10.setProperty("lightColor", QtGui.QColor(0, 0, 0, 150))
        self.CaptionLabel_10.setProperty("darkColor", QtGui.QColor(255, 255, 255, 200))
        self.CaptionLabel_10.setObjectName("CaptionLabel_10")
        self.verticalLayout_7.addWidget(self.CaptionLabel_10)
        self.CardWidget_4 = CardWidget(self.scrollAreaWidgetContents)
        self.CardWidget_4.setMinimumSize(QtCore.QSize(0, 70))
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.CardWidget_4)
        self.horizontalLayout_6.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = PushButton(self.CardWidget_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.CardWidget_4)
        self.CardWidget_5 = CardWidget(self.scrollAreaWidgetContents)
        self.CardWidget_5.setMinimumSize(QtCore.QSize(0, 70))
        self.CardWidget_5.setObjectName("CardWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.CardWidget_5)
        self.horizontalLayout_7.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.SwitchButton = SwitchButton(self.CardWidget_5)
        self.SwitchButton.setObjectName("SwitchButton")
        self.horizontalLayout_7.addWidget(self.SwitchButton)
        self.verticalLayout_7.addWidget(self.CardWidget_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_9.addLayout(self.verticalLayout_12)
        self.blank = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.blank.setMinimumSize(QtCore.QSize(0, 25))
        self.blank.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.blank.setLineWidth(5)
        self.blank.setObjectName("blank")
        self.verticalLayout_9.addWidget(self.blank)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.SmoothScrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "Class Widgets签到设置"))
        self.pushButton.setText(_translate("Form", "打开签到程序"))
from qfluentwidgets import CaptionLabel, CardWidget, PushButton, SmoothScrollArea, SubtitleLabel, SwitchButton, TitleLabel
