# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qiandao.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 1341, 651))
        self.widget.setStyleSheet("QWidget#widget{background-color:rgb(245, 245, 245);;\n"
"border-radius:20px;}")
        self.widget.setObjectName("widget")
        self.underline = QtWidgets.QWidget(self.widget)
        self.underline.setGeometry(QtCore.QRect(0, 40, 1491, 2))
        self.underline.setStyleSheet("background-color:rgb(200, 200, 200);")
        self.underline.setObjectName("underline")
        self.title = QtWidgets.QLabel(self.widget)
        self.title.setGeometry(QtCore.QRect(10, 6, 251, 31))
        self.title.setStyleSheet("font: 13pt \"黑体\";")
        self.title.setObjectName("title")
        self.peoplenum = QtWidgets.QLabel(self.widget)
        self.peoplenum.setGeometry(QtCore.QRect(440, 160, 261, 231))
        self.peoplenum.setStyleSheet("font: 100pt \"黑体\";")
        self.peoplenum.setObjectName("peoplenum")
        self.underline_2 = QtWidgets.QWidget(self.widget)
        self.underline_2.setGeometry(QtCore.QRect(750, 40, 2, 630))
        self.underline_2.setStyleSheet("background-color: rgb(200, 200, 200)")
        self.underline_2.setObjectName("underline_2")
        self.qiandaonum = QtWidgets.QLabel(self.widget)
        self.qiandaonum.setGeometry(QtCore.QRect(110, 160, 261, 231))
        self.qiandaonum.setStyleSheet("font: 100pt \"黑体\";")
        self.qiandaonum.setObjectName("qiandaonum")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(320, 160, 141, 231))
        self.label_2.setStyleSheet("font: 110pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.yidaostudents = QtWidgets.QWidget(self.widget)
        self.yidaostudents.setGeometry(QtCore.QRect(770, 60, 561, 271))
        self.yidaostudents.setStyleSheet("QWidget#yidaostudents{background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}\n"
"")
        self.yidaostudents.setObjectName("yidaostudents")
        self.title_2 = QtWidgets.QLabel(self.yidaostudents)
        self.title_2.setGeometry(QtCore.QRect(20, 10, 251, 31))
        self.title_2.setStyleSheet("font: 13pt \"黑体\";")
        self.title_2.setObjectName("title_2")
        self.textEdit = QtWidgets.QTextEdit(self.yidaostudents)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 531, 191))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 10pt \"黑体\";")
        self.textEdit.setObjectName("textEdit")
        self.weidaostudents = QtWidgets.QWidget(self.widget)
        self.weidaostudents.setGeometry(QtCore.QRect(770, 350, 561, 281))
        self.weidaostudents.setStyleSheet("QWidget#weidaostudents{background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}\n"
"")
        self.weidaostudents.setObjectName("weidaostudents")
        self.title_3 = QtWidgets.QLabel(self.weidaostudents)
        self.title_3.setGeometry(QtCore.QRect(20, 10, 251, 31))
        self.title_3.setStyleSheet("font: 13pt \"黑体\";")
        self.title_3.setObjectName("title_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.weidaostudents)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 60, 531, 191))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 10pt \"黑体\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, -700, 1341, 701))
        self.widget_2.setStyleSheet("QWidget#widget_2{background-color: rgba(222, 222, 222,160);}")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(300, 30, 781, 481))
        self.widget_3.setStyleSheet("QWidget#widget_3{background-color: rgb(255, 255, 255);\n"
"border-radius:20px;}")
        self.widget_3.setObjectName("widget_3")
        self.title_4 = QtWidgets.QLabel(self.widget_3)
        self.title_4.setGeometry(QtCore.QRect(20, 10, 251, 31))
        self.title_4.setStyleSheet("font: 13pt \"黑体\";")
        self.title_4.setObjectName("title_4")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(20, 40, 741, 361))
        self.widget_4.setObjectName("widget_4")
        # 创建 QScrollArea
        self.scrollArea = QtWidgets.QScrollArea(self.widget_4)  # 滚动区域
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 741, 361))
        self.scrollArea.setWidgetResizable(True)  # 让内容自动适应

        # 创建存放 checkbox 的 QWidget
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)  # 把这个 widget 作为滚动区域的内容

        # 在 scrollAreaWidgetContents 里创建 QGridLayout，专门用于存放 checkbox
        self.grid_layout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)

        self.pushButton = PushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(330, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = PushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 10, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = PushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 440, 311, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = PushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(1204, 8, 121, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3.raise_()
        self.underline.raise_()
        self.title.raise_()
        self.peoplenum.raise_()
        self.underline_2.raise_()
        self.qiandaonum.raise_()
        self.label_2.raise_()
        self.yidaostudents.raise_()
        self.weidaostudents.raise_()
        self.widget_2.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Class Widgets 签到"))
        self.peoplenum.setText(_translate("MainWindow", "00"))
        self.qiandaonum.setText(_translate("MainWindow", "00"))
        self.label_2.setText(_translate("MainWindow", "/"))
        self.title_2.setText(_translate("MainWindow", "已到"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.title_3.setText(_translate("MainWindow", "未到"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.title_4.setText(_translate("MainWindow", "签到"))
        self.pushButton.setText(_translate("MainWindow", "签到"))
        self.pushButton_2.setText(_translate("MainWindow", "关闭"))
        self.pushButton_3.setText(_translate("MainWindow", "签到"))
        self.pushButton_4.setText(_translate("MainWindow", "上传学生名单"))
from qfluentwidgets import PushButton
