# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 589)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(24, 24, 24, 0)
        self.verticalLayout_2.setSpacing(18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout_2.addWidget(self.TitleLabel)
        self.SmoothScrollArea = SmoothScrollArea(Form)
        self.SmoothScrollArea.setStyleSheet("background: transparent; border: none")
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 640, 528))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SubtitleLabel_2 = SubtitleLabel(self.scrollAreaWidgetContents)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.verticalLayout_7.addWidget(self.SubtitleLabel_2)
        self.CardWidget_3 = CardWidget(self.scrollAreaWidgetContents)
        self.CardWidget_3.setMinimumSize(QtCore.QSize(0, 70))
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CardWidget_3)
        self.horizontalLayout_5.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.open_names_list = PrimaryPushButton(self.CardWidget_3)
        self.open_names_list.setObjectName("open_names_list")
        self.horizontalLayout_5.addWidget(self.open_names_list)
        self.verticalLayout_7.addWidget(self.CardWidget_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)

        self.verticalLayout_9.addWidget(self.blank)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.SmoothScrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "Class Widget 签到"))
        self.SubtitleLabel_2.setText(_translate("Form", "设置"))
        self.open_names_list.setText(_translate("Form", "打开签到程序"))
from qfluentwidgets import CardWidget, PrimaryPushButton, SmoothScrollArea, SubtitleLabel, TitleLabel
